# The ATP form, containerised. Same application as `python3 build/serve.py`
# locally - the contract is generated by build.py either way.
FROM python:3.12-slim

# python-docx needs lxml; the slim image has no compiler, so take the wheel.
RUN pip install --no-cache-dir "python-docx==1.1.2" "PyMuPDF==1.24.10"

WORKDIR /app

# The template and its data are baked into the image on purpose: a contract can
# only be issued from a version of the template that was deployed, which ties
# issuance to something reviewed.
COPY build/ build/
COPY template/ template/
COPY presets/ presets/
COPY jurisdictions/ jurisdictions/
COPY engagements/_starter.json engagements/_starter.json

ENV ATP_HOST=0.0.0.0 \
    ATP_PORT=8080 \
    ATP_OPEN_BROWSER=0 \
    PYTHONUNBUFFERED=1

EXPOSE 8080

CMD ["python3", "build/serve.py"]
